[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "spex"
version = "0.6.0"
requires-python = ">=3.9"
dependencies = [
    "jinja2",
    'tomli>=1.0; python_version < "3.11"',
]

[tool.setuptools]
py-modules = []
packages = []

[project.optional-dependencies]
dev = [
    "ruff",
    "pytest",
    "pytest-cov",
    "pytest-xdist",
]
